### ISSUE TITLE
大佬，使用pip安装依赖时报错

### ISSUE THREAD

**Issue by JackZho** [huajien/ZXJY_DK#1]
Requirement already satisfied: h11<0.15,>=0.13 in d:\program files\python\lib\site-packages (from httpcore->httpx<1,>=0.23.0->openai>=0.28->-r requirements.txt (line 3)) (0.14.0)
Building wheels for collected packages: cChardet
Building wheel for cChardet (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for cChardet (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [22 lines of output]
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-cpython-310
    creating build\lib.win-amd64-cpython-310\cchardet
    copying src\cchardet\version.py -> build\lib.win-amd64-cpython-310\cchardet
    copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-310\cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    creating build\temp.win-amd64-cpython-310
    creating build\temp.win-amd64-cpython-310\Release
    creating build\temp.win-amd64-cpython-310\Release\src
    creating build\temp.win-amd64-cpython-310\Release\src\cchardet
    creating build\temp.win-amd64-cpython-310\Release\src\ext
    creating build\temp.win-amd64-cpython-310\Release\src\ext\uchardet
    creating build\temp.win-amd64-cpython-310\Release\src\ext\uchardet\src
    creating build\temp.win-amd64-cpython-310\Release\src\ext\uchardet\src\LangModels
    "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ext/uchardet/src "-ID:\Program Files\python\include" "-ID:\Program Files\python\Include" "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -ID:\DeliveryOptimization\SoftWare\WindowsSDK /EHsc /Tpsrc/cchardet\_cchardet.cpp /Fobuild\temp.win-amd64-cpython-310\Release\src/cchardet\_cchardet.obj
    _cchardet.cpp
    d:\program files\python\include\pyconfig.h(200): fatal error C1083: 无法打开包括文件: “basetsd.h”: No such file or directory
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for cChardet
Failed to build cChardet
ERROR: Could not build wheels for cChardet, which is required to install pyproject.toml-based projects

**Comment by huajien** [comment]
缺少Windows SDK可以尝试使用安装
Windows SDK
https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

或使用手动安装python库 cChardet 
下载对应版本https://pypi.org/project/cchardet/#files
python  **cchardet\*.whl**

**Comment by JackZho** [comment]
已解决，非常感谢！
