### ISSUE TITLE
version.py 中的 AdaptedVersion 的值没有更新

### ISSUE THREAD

**Issue by 321930869** [huajien/ZXJY_DK#10]
如题，0.48 版本中 version.py 文件中的 AdaptedVersion 变量的值没有更新，仍为 v1.4.1，最新版为 v1.4.4

![image](https://github.com/huajien/ZXJY_DK/assets/38862316/63caee27-de21-47b3-bad8-d323474d85df)

**Comment by huajien** [comment]
收到感谢您的反馈
我抽空看一下软件更新了什么

**Comment by 3350489681** [comment]
新的文件中version.py文件中1.4.1未修改 自行修改1.4.4可以正常使用 感谢老哥
