### ISSUE TITLE
[BUG] 周报开始时间计算逻辑错误

### ISSUE THREAD

**Issue by 321930869** [huajien/ZXJY_DK#11]
#### 描述
这个 bug 是关于周报时间区间计算的，当前实现的周报开始时间的计算逻辑不太对，计算后所得的时间是上周日而非当前周的周一，导致周报时间段实际上包含了8天，而不是标准的一周7天。

#### 相关代码
 sendReport.py 文件中的第 119 行和 120 行（好吧，实际上是一行代码(￣y▽,￣)╭ ）
![image](https://github.com/huajien/ZXJY_DK/assets/38862316/33113ead-53b8-4d46-9190-50878bb7e92b)

#### 解决方案
将上述代码中的时间差从7天改为6天即可
![image](https://github.com/huajien/ZXJY_DK/assets/38862316/fdc000f5-4f67-4faa-894b-20b2f6a05f87)

**Comment by huajien** [comment]
感谢> [321930869](https://github.com/321930869) 提出问题和解决方案目


**已修复**
