### ISSUE TITLE
版本匹配

### ISSUE THREAD

**Issue by PPQ0501** [huajien/ZXJY_DK#13]
version值已经更1.4.4了 职校家园最新也是1.4.4 提示系统更新版本不匹配

**Comment by PPQ0501** [comment]
解决了ZxjyVersion = 0.193更改0.49 谢谢大佬

**Comment by huajien** [comment]
不意思昨天赶着走呢，代码推的有点急没有注意测试代码。抱歉
今天晚上或者明天晚上到了后改一下
