### ISSUE TITLE
职校家园更新问题反馈

### ISSUE THREAD

**Issue by 321930869** [huajien/ZXJY_DK#16]
如题，又更新了，望适配一下。
目前测试直接更改`version.py`文件中的 `AdaptedVersion` 的值为`v1.4.5`后，是可以正常打卡的。

**Comment by huajien** [comment]
收到感谢反馈

**Comment by 321930869** [comment]
> 收到感谢反馈

麻蛋，职校家园又双叒叕更新了😒，更新到 `v1.4.6` 了，刚刚代码里改了版本号之后测试打卡能打上，应该没啥问题

**Comment by huajien** [comment]
昨天卧更新了只放在暂存区了忘记推送了抱歉
---- 回复的原邮件 ----
***@***.***>发送日期2024年03月28日 08:11 ***@***.***> ***@***.***>,
***@***.***>主题Re: [huajien/ZXJY_DK] 职校家园又更新了，目前版本号是 v1.4.5 (Issue #16)
收到感谢反馈
麻蛋，职校家园又双叒叕更新了😒，更新到 v1.4.6 了，刚刚代码里改了版本号之后测试打卡能打上，应该没啥问题
