### ISSUE TITLE
职校家园更新

### ISSUE THREAD

**Issue by gfh980** [huajien/ZXJY_DK#17]
version.py 文件里     AdaptedVersion 改为 'v1.4.7'可正常使用

**Comment by gfh980** [comment]
我只改了这个版本号可以正常打卡，其他问题没见，还望大哥确认一下

**Comment by huajien** [comment]
我今天凌晨已经更新了版本不需要手动改
可以试试定义启动时候自动拉去新版本这样就不用管了

```bash
git fetch --all && git reset --hard origin/master

```
结合Linux crontab并定时命令 
`56 7 * * * cd ~/ZXJY_DK && git fetch --all && git reset --hard origin/master && mkdir -p log && python3 main.py >> log/$(date +"\%Y-\%m-\%d").log 2>&1`

访问

[查看命令参数](https://github.com/huajien/ZXJY_DK#%E9%85%8D%E7%BD%AE%E6%AF%8F%E5%A4%A9%E5%AE%9A%E6%97%B6%E8%87%AA%E5%8A%A8%E6%89%93%E5%8D%A1)

**Comment by gfh980** [comment]
> 我今天凌晨已经更新了版本不需要手动改 可以试试定义启动时候自动拉去新版本这样就不用管了
> 
> ```shell
> git fetch --all && git reset --hard origin/master
> ```
> 
> 结合Linux crontab并定时命令 `56 7 * * * cd ~/ZXJY_DK && git fetch --all && git reset --hard origin/master && mkdir -p log && python3 main.py >> log/$(date +"\%Y-\%m-\%d").log 2>&1`
> 
> 访问
> 
> [查看命令参数](https://github.com/huajien/ZXJY_DK#%E9%85%8D%E7%BD%AE%E6%AF%8F%E5%A4%A9%E5%AE%9A%E6%97%B6%E8%87%AA%E5%8A%A8%E6%89%93%E5%8D%A1)

好的感谢大哥解答

**Comment by gfh980** [comment]
![image](https://github.com/huajien/ZXJY_DK/assets/151613844/1b7cc504-a674-4649-879b-7ad1e723b1a2)
哥这是什么问题

**Comment by gfh980** [comment]
> 日报得问题 我抽空看一下这几天在家休息 ---- 回复的原邮件 ---- ***@***.***>发送日期2024年05月02日 09:31 ***@***.***> ***@***.***>, ***@***.***>主题Re: [huajien/ZXJY_DK] 职校家园更新 (Issue #17) image.png (view on web) 哥这是什么问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的哥

**Comment by huajien** [comment]
已修复更新即可

**Comment by gfh980** [comment]
> 已修复更新即可

![image](https://github.com/huajien/ZXJY_DK/assets/151613844/c56dc961-6658-4aa1-b57e-fefbd5bdd9ee)
哥日报还有点问题

**Comment by huajien** [comment]
可以在开一个 issues 要不然不好管理那个问题 一个issues 管理一个问题逐个解决 要不然一个弄一大堆太麻烦了

我用的邮件通知有问题总是收不到邮件信息 
见谅
