### ISSUE TITLE
压缩包新解压 出来 不添加数据 直接运行main.py 有第一次保存的数据  之前的文件夹删了都不行

### ISSUE THREAD

**Issue by WangYi8** [huajien/ZXJY_DK#18]
压缩包新解压 出来 不添加数据 直接运行main.py 有第一次保存的数据  之前的文件夹删了都不行 还找不到在哪
![捕获](https://github.com/huajien/ZXJY_DK/assets/84239066/b0591122-9041-49e4-ac5c-2925fb572ef6)
![捕获1](https://github.com/huajien/ZXJY_DK/assets/84239066/53c7cffc-e1ed-4dc8-bf5f-42e6a9124351)

**Comment by huajien** [comment]
您那边找一下`userData.json`文件
