### ISSUE TITLE
运行多用户打卡 只运行20个就闪退了

### ISSUE THREAD

**Issue by WangYi8** [huajien/ZXJY_DK#19]
运行多用户打卡 只运行20个就闪退了

**Comment by huajien** [comment]
您这边能说清楚点吗我这边好修复

**Comment by huajien** [comment]
是不是 json 格式错了，我这边刚刚测试几百个都没问题呀

**Comment by WangYi8** [comment]
对 json错了 ，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月2日(周二) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huajien/ZXJY_DK] 运行多用户打卡 只运行20个就闪退了 (Issue #19)




 
是不是 json 格式错了，我这边刚刚测试几百个都没问题呀
