### ISSUE TITLE
日报系统ChatGPT中缺少键

### ISSUE THREAD

**Issue by gfh980** [huajien/ZXJY_DK#20]
![image](https://github.com/huajien/ZXJY_DK/assets/151613844/5ed72fb5-fa75-4f8b-acbc-fe41c923b5dd)

**Comment by huajien** [comment]
我早上时候推送了 [
修复填写报告错误问题](https://github.com/huajien/ZXJY_DK/commit/d2d2d50dea9c6f1054ba739e9fcd8de13174f96b)
你更新后试试

**Comment by gfh980** [comment]
> 我早上时候推送了 [ 修复填写报告错误问题](https://github.com/huajien/ZXJY_DK/commit/d2d2d50dea9c6f1054ba739e9fcd8de13174f96b) 你更新后试试

![image](https://github.com/huajien/ZXJY_DK/assets/151613844/a880028f-ac36-4881-ae20-5d3d3c2618a4)
哥我把代码重新下载安装后还是这个问题

**Comment by huajien** [comment]
不应该呀 我测试没用问题呀你全文本覆盖吗
---- 回复的原邮件 ----
***@***.***>发送日期2024年05月07日 21:31 ***@***.***> ***@***.***>,
***@***.***>主题Re: [huajien/ZXJY_DK] 日报系统ChatGPT中缺少键 (Issue #20)
我早上时候推送了 修复填写报告错误问题 你更新后试试
image.png (view on web)
哥我把代码重新下载安装后还是这个问题

**Comment by gfh980** [comment]
我用宝塔面板跟电脑测试了几次都是报错

**Comment by huajien** [comment]
您那边在尝试一下，我这边测试均没有这种情况。
