### ISSUE TITLE
大哥我可以免费给你提供个带日报网页端代码

### ISSUE THREAD

**Issue by gfh980** [huajien/ZXJY_DK#24]
您如果需要我可以免费提供给您，我是用的你的后端代码，我去年买了个前端的改了改适配了您这个代码。

**Comment by gfh980** [comment]
因为今年我用不到了，所以想着提供给大哥您

**Comment by huajien** [comment]
不用了兄弟 我也没有多长时间更新 我可以自己写 web 端但是我感觉没有必要这种命令行就行了 web 版本的肯定会有人想商用收费什么的。

**Comment by gfh980** [comment]
> 不用了兄弟 我也没有多长时间更新 我可以自己写 web 端，但是我感觉没有必要这种命令行就行了 web 版本的肯定会有人想商用收费什么的。

好的大哥
