### ISSUE TITLE
运行日报失败ChatGPT中缺少键: '实习项目'第1重试

### ISSUE THREAD

**Issue by a23200** [huajien/ZXJY_DK#25]
打卡能成功打卡，在日报周报填写的时候提示ChatGPT中缺少键: '实习项目'第1重试，是怎么回事，请大佬解惑

**Comment by huajien** [comment]
ai调教问题

**Comment by a23200** [comment]
那这个问题该咋解决，大佬

**Comment by huajien** [comment]
> 那这个问题该咋解决，大佬

修改 sendReport.py文件的gptReport.gptConfig里面的参数优化他

**Comment by huajien** [comment]
好像就是有问题，我今天借一下账号测试一下

**Comment by huajien** [comment]
新版本已经推送昨天中午出去了忘记推送，可以试试新的gpt 词

**Comment by a23200** [comment]
> 新版本已经推送昨天中午出去了忘记推送，可以试试新的gpt 词

刚刚更新了试了下，还是一样的问题
![image](https://github.com/huajien/ZXJY_DK/assets/60913279/47c8de2b-d235-47d7-9f1b-879b03164d60)

**Comment by huajien** [comment]
重复几次后呢一般不超过 10 词就没事

**Comment by huajien** [comment]
优化了处理 gpt 返回数据的处理
可以升级最新版0.501版本
您可以使用
```base
git fetch --all && git reset --hard origin/master
```
更新最新版本

**Comment by a23200** [comment]
![image](https://github.com/huajien/ZXJY_DK/assets/60913279/2c931010-452b-421b-8699-db69bdd13712)
倒是又另一种错误了，或许是我环境问题？又得麻烦您看看了

**Comment by huajien** [comment]
岗位名称能发我一下吗

**Comment by huajien** [comment]
或者您重新获取一下代码 看你这大概率可能是 调用的 openai 没有返回数据sendReport.py文件 63 行 dailyRreportContent这个变量为空
<img width="1486" alt="image" src="https://github.com/huajien/ZXJY_DK/assets/75553778/875bc15d-5587-4554-bde4-11b1eda2a8e8">
或者您使用的 api 的 key 不对
在这里看一下
[https://api.chatanywhere.org/v1/oauth/free/github/render](https://api.chatanywhere.org/v1/oauth/free/github/render)

对比
`aiReport.json`文件

**Comment by a23200** [comment]
> 岗位名称能发我一下吗

音乐助教

**Comment by a23200** [comment]
{'error': "OpenAI API 异常: module 'openai' has no attribute 'ChatCompletion
输出了这个，或许是我openai的版本不对，我用的是Linux环境，自动安装的是0.15.0（源下的最高版本），

**Comment by huajien** [comment]
> {'error': "OpenAI API 异常: module 'openai' has no attribute 'ChatCompletion 输出了这个，或许是我openai的版本不对，我用的是Linux环境，自动安装的是0.15.0（源下的最高版本），

您可以先卸载0.15
`pip3 uninstall openai`
或者
`pip uninstall openai`

安装
`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple openai==0.28`
或者
`pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple openai==0.28`


查看安装的版本
`pip show openai`
或者
`pip3 show openai`

**Comment by a23200** [comment]
> > {'error': "OpenAI API 异常: module 'openai' has no attribute 'ChatCompletion 输出了这个，或许是我openai的版本不对，我用的是Linux环境，自动安装的是0.15.0（源下的最高版本），
> 
> 您可以先卸载0.15 `pip3 uninstall openai` 或者 `pip uninstall openai`
> 
> 安装 `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple openai==0.28` 或者 `pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple openai==0.28`
> 
> 查看安装的版本 `pip show openai` 或者 `pip3 show openai`

您看下，清华的源里没有0.28

**Comment by huajien** [comment]
> > > {'error': "OpenAI API 异常: module 'openai' has no attribute 'ChatCompletion 输出了这个，或许是我openai的版本不对，我用的是Linux环境，自动安装的是0.15.0（源下的最高版本），
> > 
> > 
> > 您可以先卸载0.15 `pip3 uninstall openai` 或者 `pip uninstall openai`
> > 安装 `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple openai==0.28` 或者 `pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple openai==0.28`
> > 查看安装的版本 `pip show openai` 或者 `pip3 show openai`
> 
> 您看下，清华的源里没有0.28

我刚在里面下载了z'm怎么可能没有
<img width="1367" alt="image" src="https://github.com/huajien/ZXJY_DK/assets/75553778/7f806637-2660-4bb9-b6ca-7a118d08d85d">

**Comment by a23200** [comment]
谢谢，罪魁祸首就是Linux自带的python3是3.6.8，但是openai0.28只支持3.7以上，导致我安装不上0.25以上，重新换了python版本已经解决，感谢！
