### ISSUE TITLE
ChatGPT中缺少键: '实习项目'第1重试

### ISSUE THREAD

**Issue by douoai** [huajien/ZXJY_DK#27]
最新的版本更新后也是这个错误

**Comment by huajien** [comment]
重试肯定有几次呢一般不超过 10 次新版

**Comment by douoai** [comment]
![Snipaste_2024-07-02_21-05-02](https://github.com/huajien/ZXJY_DK/assets/62254609/c5fe97e4-ea6b-47b4-8423-d7b4a325ef5d)
可能还是ai的关键词有问题

**Comment by huajien** [comment]
优化了处理 gpt 返回数据的处理
可以升级最新版0.501版本
您可以使用
```base
git fetch --all && git reset --hard origin/master
```
更新最新版本
