### ISSUE TITLE
周报程序报错

### ISSUE THREAD

**Issue by JackZho** [huajien/ZXJY_DK#3]
大佬你好，运行sendReport.py程序时出现了以下报错是哪里的问题呀？
Traceback (most recent call last):
  File "d:\Download\01_职校家园\ZXJY_DK\sendReport.py", line 233, in <module>
    main.main()
TypeError: main() missing 1 required positional argument: 'AllUsers'

**Comment by huajien** [comment]
感谢（[JackZho](https://github.com/JackZho)）提出报错信息
已经找到问题
并已修复
**其他函数调用main报错**

**Comment by JackZho** [comment]
大佬，还是不能周报填写呀，
运行sendReport.py程序后，只显示打卡的这些信息，没显示进行日报、周报、月报PS 
```
D:\Download\01_职校家园\ZXJY_DK> & "D:/Program Files/python/python.exe" d:/Download/01_职校家园/ZXJY_DK/sendReport.py
存在userData.json文件
不输入默认60秒自动进行打卡当前用户列表
是否添加新用户 y or n（默认n执行单次打卡）：
n
user 延时 61 秒
user 打卡时间 2023-11-19 14:29:49
user 未启用打卡，即将跳过
```

**Comment by JackZho** [comment]
客气了大佬，应该我谢你才对，现在还有一个问题就是使用sendReport.py进行日报、周报、月报操作时，出现以下提示：
```
用户张三 开启日报
当前状态是正在实习
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
用户张三 开启周报
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
```

**Comment by huajien** [comment]
> 客气了大佬，应该我谢你才对，现在还有一个问题就是使用 sendReport.py 进行日报、周报、月报操作时，出现以下提示：
> 
> ```
> 用户张三 开启日报
> 当前状态是正在实习
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 用户张三 开启周报
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> 未找到 Error: 'content'
> ```

这个报错，应该是我写的读取当前岗位名称<br>
没有读取到相应的岗位名称`data['data']['bmlist'][0]['gwName']`
可以在 53行data = response.json()
替换为 
```python
data = response.json()
print(data)
```
添加后会回显信息
记得将个人信息处理一下反馈给我


例如
```json
{
	'code': 1001,
	'deviceId': '',
	'data': {
		'bmcheck': False,
		'bmcount': 2,
		'bmmsg': '',
		'bmlist': [{
			'bmid': '000',
			'jobid': '000',
			'gwName': '信息安全员',
			'companyName': '河南有限公司',
			'gzdd': '河南',
			'salary': '0 ',
			'bmstatus': '正在实习',
			'sdate': '',
			'msgcolor': '#FFD700',
			'next': 2
		}, {
			'bmid': '0000',
			'jobid': '00000',
			'gwName': '信息安全员',
			'companyName': '河南有限公司',
			'gzdd': '河南',
			'salary': '0',
			'bmstatus': '实习解约',
			'sdate': '',
			'msgcolor': '#4F9FE8',
			'next': 0
		}]
	},
	'msg': '',
	'currentpage': 0,
	'pagesize': 0,
	'totalcount': 0,
	'pagecount': 0
}
```

**Comment by JackZho** [comment]
`{'code': 1001, 'deviceId': '', 'data': {'bmcheck': False, 'bmcount': 1, 'bmmsg': '', 'bmlist': [{'bmid': '1459306', 'jobid': '1451161', 'gwName': '测量员', 'companyName': '郑州本初装饰工程有限公司', 'gzdd': '河南省郑州市金水区鑫苑金融广场', 'salary': '2k-3k', 'bmstatus': '正在实习', 'sdate': '', 'msgcolor': '#FFD700', 'next': 2}]}, 'msg': '', 'currentpage': 0, 'pagesize': 0, 'totalcount': 0, 'pagecount': 0}`

**Comment by JackZho** [comment]
`{'code': 1001, 'deviceId': '', 'data': {'bmcheck': False, 'bmcount': 1, 'bmmsg': '', 'bmlist': [{'bmid': '1459306', 'jobid': '1451161', 'gwName': '测量员', 'companyName': '郑州本初装饰工程有限公司', 'gzdd': '河南省郑州市金水区鑫苑金融广场', 'salary': '2k-3k', 'bmstatus': '正在实习', 'sdate': '', 'msgcolor': '#FFD700', 'next': 2}]}, 'msg': '', 'currentpage': 0, 'pagesize': 0, 'totalcount': 0, 'pagecount': 0}`

**Comment by huajien** [comment]
> `{'code': 1001, 'deviceId': '', 'data': {'bmcheck': False, 'bmcount': 1, 'bmmsg': '', 'bmlist': [{'bmid': '1459306', 'jobid': '1451161', 'gwName': '测量员', 'companyName': '郑州本初装饰工程有限公司', 'gzdd': '河南省郑州市金水区鑫苑金融广场', 'salary': '2k-3k', 'bmstatus': '正在实习', 'sdate': '', 'msgcolor': '#FFD700', 'next': 2}]}, 'msg': '', 'currentpage': 0, 'pagesize': 0, 'totalcount': 0, 'pagecount': 0}`

后面可以还是报错吗

**Comment by JackZho** [comment]
```
用户张三 开启日报 {
    'code': 1001,
    'deviceId': '',
    'data': {
        'bmcheck': False,
        'bmcount': 1,
        'bmmsg': '',
        'bmlist': [{
                    'bmid': '1459306',
                    'jobid': '1451161',
                    'gwName': '测量员',
                    'companyName': '郑州本初装饰工程有限公司',
                    'gzdd': '河南省郑州市金水区鑫苑金融广场',
                    'salary': '2k-3k',
                    'bmstatus': '正在实习',
                    'sdate': '',
                    'msgcolor': '#F当前状态是正在实习
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
用户张三 开启周报
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
未找到 Error: 'content'
```

**Comment by huajien** [comment]
python中的openai库版本
错误可以尝试使用
`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ openai==0.28.0`
升级为**0.28.0**版本

**Comment by JackZho** [comment]
大佬你好，error的报错升级openai版本后已经解决，也可以进行日报/周报操作。
以下是我对sendReport.py程序的一点儿建议
1.建议给不同的用户设置日报开关，因为有的专业是不用交日报的。
2.增加日报（也可以是周报/月报）自定义日期选项，例如（日报起始日期9.3，日报终止日期10.11，每篇日报间最好有1-2分钟的间隔）。
3.设置打卡自由化，即可以单独使用日报程序，而不执行打卡。
以上意见仅供参考。
大佬可否发个收款码？你的项目对我帮助很大，想请你喝杯奶茶。

**Comment by huajien** [comment]
1、新版本已经加入此功能重新拉取代码即可
2、这个功能等后面我在考虑下周要去出差比较忙没有时间弄
3、新版本已经加入
最后暂时不考虑
