### ISSUE TITLE
代码细节问题

### ISSUE THREAD

**Issue by JackZho** [huajien/ZXJY_DK#4]
大佬你好，我发现sendReport.py中的第33行代码输出问题有误，应该是日报信息gpt已完成准备填写周报
![image](https://github.com/huajien/ZXJY_DK/assets/53811022/da7c0674-8afd-44e8-afa6-6354c69fc0b5)

**Comment by huajien** [comment]
> 大佬你好，我发现sendReport.py中的第33行代码输出问题有误，应该是日报信息gpt已完成准备填写周报
> ![image](https://github.com/huajien/ZXJY_DK/assets/53811022/da7c0674-8afd-44e8-afa6-6354c69fc0b5)
> 

谢谢您提出提出的问题
首先周报我认为不是每天都执行
所以我认为没有问题

**Comment by JackZho** [comment]
奥，你说的对




　&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;　
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huajien/ZXJY_DK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 上午8:17
***@***.***&gt;;
抄送:&nbsp;"　           ***@***.******@***.***&gt;;
主题:&nbsp;Re: [huajien/ZXJY_DK] 代码细节问题 (Issue #4)



  大佬你好，我发现sendReport.py中的第33行代码输出问题有误，应该是日报信息gpt已完成准备填写周报
 
  谢谢您提出提出的问题
 首先周报我认为不是每天都执行
 所以我认为没有问题
