### ISSUE TITLE
大哥放宝塔可以用吗？

### ISSUE THREAD

**Issue by gfh980** [huajien/ZXJY_DK#5]

**Comment by huajien** [comment]
可以的

**Comment by gfh980** [comment]
![5477a1a54a7e42d358936c29295f7f3](https://github.com/huajien/ZXJY_DK/assets/151613844/90433bef-1167-4fb8-a000-d2eb1fe4813b)
大哥这是什么问题

**Comment by huajien** [comment]
> ![5477a1a54a7e42d358936c29295f7f3](https://private-user-images.githubusercontent.com/151613844/289093786-90433bef-1167-4fb8-a000-d2eb1fe4813b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDQ4NTIsIm5iZiI6MTcwMjA0NDU1MiwicGF0aCI6Ii8xNTE2MTM4NDQvMjg5MDkzNzg2LTkwNDMzYmVmLTExNjctNGZiOC1hMDAwLWQyZWIxZmU0ODEzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQxNDA5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDUwYzc0NTYyOTdjNjk1NDhlZmM0YTQ1ZmYzYTQwMTJlM2NjNGFlMDk2NDllNzA4ZmU2ZmE1N2RiNjQyZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YFzlHbNLBhfHrxfiNTwQBfSVOpO12akvERwHbpeWmJA) 大哥这是什么问题

你可以尝试升级`python` 版本值 `3.8` 以上

**Comment by gfh980** [comment]
大哥疑似作弊是什么问题

**Comment by huajien** [comment]
可以发来看看吗你的延迟时间什么得改了吗
---- 回复的原邮件 ----
***@***.***>发送日期2024年03月28日 19:23 ***@***.***> ***@***.***>,
***@***.***>主题Re: [huajien/ZXJY_DK] 大哥放宝塔可以用吗？ (Issue #5)
大哥疑似作弊是什么问题

**Comment by huajien** [comment]
我抽空分析一下新版app看看更新啥检测没
---- 回复的原邮件 ----
***@***.***>发送日期2024年03月28日 19:23 ***@***.***> ***@***.***>,
***@***.***>主题Re: [huajien/ZXJY_DK] 大哥放宝塔可以用吗？ (Issue #5)
大哥疑似作弊是什么问题

**Comment by gfh980** [comment]
> 可以发来看看吗你的延迟时间什么得改了吗 ---- 回复的原邮件 ---- @***.***>发送日期2024年03月28日 19:23 ***@***.***> ***@***.***>, @***.***>主题Re： [huajien/ZXJY_DK] 大哥放宝塔可以用吗？ （问题 #5） 大哥疑似作弊是什么问题 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您发表了评论。消息 ID：***@***.***>

我把延迟改到1-5秒了

**Comment by huajien** [comment]
> > 可以发来看看吗你的延迟时间什么得改了吗 ---- 回复的原邮件 ---- @_**.**_>发送日期2024年03月28日 19:23 _**@**_._**> _**@**_.**_>, @_**.**_>主题Re： [huajien/ZXJY_DK] 大哥放宝塔可以用吗？ （问题 #5） 大哥疑似作弊是什么问题 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> 
> 我把延迟改到1-5秒了

时间太短了加长点服务器那边防火墙以为是攻击所以异常

**Comment by gfh980** [comment]
> > > 可以发来看看吗你的延迟时间什么得改了吗 ---- 回复的原邮件 ---- @_**.**_>发送日期2024年03月28日 19:23 _**@**_._**> _**@**_.**_>, @_**.**_>主题Re： [huajien/ZXJY_DK] 大哥放宝塔可以用吗？ （问题 #5） 大哥疑似作弊是什么问题 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您发表了评论。消息 ID：_**@**_.***>
> > 
> > 
> > 我把延迟改到1-5秒了
> 
> 时间太短了加长点服务器那边防火墙以为是攻击所以异常

感谢大哥解答
