### ISSUE TITLE
大哥我这本机运行不起来是因为啥原因

### ISSUE THREAD

**Issue by PPQ0501** [huajien/ZXJY_DK#7]
![image](https://github.com/huajien/ZXJY_DK/assets/140469589/190536ab-978a-482f-82f8-c3caaa329d9a)
![3b3218d5acfc94f2a2e4950410f1ca7](https://github.com/huajien/ZXJY_DK/assets/140469589/9398fc4f-b112-43b2-94e7-81f8ac1d8657)
![Uploading 3b3218d5acfc94f2a2e4950410f1ca7.png…]()

**Comment by huajien** [comment]
可能是库的问题
尝试使用
```bash
pip freeze | grep beautifulsoup4
```
或者
```bash

pip3 freeze | grep beautifulsoup4
```
