### ISSUE TITLE
运行sendReport.py文件报错

### ISSUE THREAD

**Issue by JackZho** [huajien/ZXJY_DK#9]
大佬你好，
我将sendReport.py文件中的代码封装成了一个fasong函数，调用这个函数时出现了以下保存信息请问应该如何处理？python版本为3.8
Traceback (most recent call last):
  File "sendReport.py", line 197, in <module>
    fasong()
  File "sendReport.py", line 195, in fasong
    main.main()
  File "/home/runner/work/dayreport/dayreport/main.py", line 26, in main
    winmain(AllUsers)
  File "/home/runner/work/dayreport/dayreport/main.py", line 9, in winmain
    parsUserConfig.LoadUserConfig(user)
  File "/home/runner/work/dayreport/dayreport/parsUserConfig.py", line 57, in LoadUserConfig
    sendReport.report(user, uid, token)
AttributeError: module 'sendReport' has no attribute 'report'
Error: Process completed with exit code 1.

**Comment by huajien** [comment]
你好你那边可以看一下
最下面的我写的是调用调用sendReport默认运行main.py文件你可以调用的时候加上要调用的函数
这几天在外面忙没啥时间看

**Comment by JackZho** [comment]
大佬你好，如果想要移除sendReport.py中的日报功能（即只保留周报以及月报功能）应该如何修改sendReport.py程序的代码，麻烦您有时间了给我指点一下。

**Comment by JackZho** [comment]
好的我试一下

**Comment by JackZho** [comment]
大佬你好，已经成功移除日报功能，但是我的日报内容是这样的`报告项目软件开发 实习记录内容本周主要负责了XXX模块的需求分析和设计工作，与团队成员合作完成了部分代码编写，并参与了代码审核和单元测试工作。同时，学习了XXX技术栈的相关知识，积极参与团队讨论和分享。 实习总结内容本周在软件开发实习中取得了一定的进步，提升了自己的需求分析和设计能力，加深了对XXX技术栈的理解，同时也加强了团队协作和沟通能力。在未来的实习中，将继续努力学习，提升自己的编码能力和项目管理能力。`能否不让它显示XXX技术栈以及XXX模块，显示具体的技术(比如说前端开发)，网页中的注册模块。这个是不是要修改sendReport.py中问chatgpt的话术？建议可以给addUsers.py增加数据项"work":(用户的实习岗位名称)，让用户自定义自己的实习岗位名称，这样程序还可以省一步抓取职校家园中用户的实习岗位名称。

**Comment by huajien** [comment]
> 大佬你好，已经成功移除日报功能，但是我的日报内容是这样的`报告项目软件开发 实习记录内容本周主要负责了XXX模块的需求分析和设计工作，与团队成员合作完成了部分代码编写，并参与了代码审核和单元测试工作。同时，学习了XXX技术栈的相关知识，积极参与团队讨论和分享。 实习总结内容本周在软件开发实习中取得了一定的进步，提升了自己的需求分析和设计能力，加深了对XXX技术栈的理解，同时也加强了团队协作和沟通能力。在未来的实习中，将继续努力学习，提升自己的编码能力和项目管理能力。`能否不让它显示XXX技术栈以及XXX模块，显示具体的技术(比如说前端开发)，网页中的注册模块。这个是不是要修改sendReport.py中问chatgpt的话术？建议可以给addUsers.py增加数据项"work":(用户的实习岗位名称)，让用户自定义自己的实习岗位名称，这样程序还可以省一步抓取职校家园中用户的实习岗位名称。




你好其实我认为用户自己定义实习岗位名称没那必要
显示xxx技术这个需要改变gpt话术还在考虑改为什么我这边测试并没有xxx问题
最后感谢 [JackZho](https://github.com/JackZho) 提出的问题

**Comment by JackZho** [comment]
他这个是偶尔会发生这样的问题，之前也发生过一次。
![Uploading IMG_20231217_200818.jpg…]()

**Comment by JackZho** [comment]
他这个是偶尔会发生这样的问题，之前也发生过一次。

![IMG_20231217_200818](https://github.com/huajien/ZXJY_DK/assets/53811022/095e2e28-3fd4-4d64-b107-debbdd645212)

**Comment by huajien** [comment]
> 他这个是偶尔会发生这样的问题，之前也发生过一次。
> 
> ![IMG_20231217_200818](https://private-user-images.githubusercontent.com/53811022/291060646-095e2e28-3fd4-4d64-b107-debbdd645212.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTU0MjgsIm5iZiI6MTcwMjgxNTEyOCwicGF0aCI6Ii81MzgxMTAyMi8yOTEwNjA2NDYtMDk1ZTJlMjgtM2ZkNC00ZDY0LWIxMDctZGViYmRkNjQ1MjEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEyMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MjVjMzc0N2IxOGMwYmVjYzhmNWYzNTgwNzFmZTAxY2QxNDIyYWIxMjI3MDcxNTI5MzViZWZhMGNlYWU4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5TS4PPVHIp_eO53PSHrUDa_QremBx6P5VQx4_yDRlpU)

行我明白了等我更新把这个好像有点问题或者你自己可以尝试优化gpt话术

**Comment by JackZho** [comment]
好的
